# Import Packages

In [1]:
import numpy as np

# Create a five element array

In [2]:
array_five = np.array([7,2,1,4,9])

In [3]:
array_five

array([7, 2, 1, 4, 9])

# Aggregate Functions

In [4]:
array_five.min()

1

In [5]:
array_five.max()

9

In [6]:
array_five.sum()

23

In [7]:
array_five.mean()

4.6

In [8]:
array_five.std()

3.006659275674582

# Create an Array of Only Ones

In [9]:
theOnes = np.ones(5)

In [10]:
theOnes

array([1., 1., 1., 1., 1.])

# Add Arrays Together

In [11]:
array_five + theOnes

array([ 8.,  3.,  2.,  5., 10.])

# Multiply Array by 4

In [12]:
array_five * 4

array([28,  8,  4, 16, 36])

# Call the 4th Element Using Indexing

In [13]:
array_five[3]

4

# Create an 8 element 4x2 matrix

In [14]:
matrixMeCrazy = np.array([[1,2,3,4], [5,6,7,8]])

In [15]:
matrixMeCrazy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Access the Bottom Right Element

In [16]:
matrixMeCrazy[1,3]

8

# Reshape the Matrix to 2x4

In [19]:
matrixMeCrazy.reshape(1,7)

ValueError: cannot reshape array of size 8 into shape (1,7)