<img src="https://numpy.org/doc/stable/_static/numpylogo.svg" align="left" alt="Python image" width = "300">

# NumPy Basics

- [What is NumPy?](https://numpy.org/doc/stable/user/whatisnumpy.html)
- [NumPy Quickstart](https://numpy.org/doc/stable/user/quickstart.html)

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

The points about sequence size and speed are particularly important in scientific computing. As a simple example, consider the case of multiplying each element in a 1-D sequence with the corresponding element in another sequence of the same length. If the data are stored in two Python lists, a and b, we could iterate over each element:

In [193]:
# you can create a simple list in python
import random

a = [random.randrange(1, 50, 1) for i in range(7)]
print ("Random number list is : " +  str(a))

b = [random.randrange(1, 50, 1) for i in range(7)]
print ("Random number list is : " +  str(b))

Random number list is : [15, 13, 23, 6, 23, 48, 34]
Random number list is : [13, 35, 11, 2, 34, 4, 21]


In [194]:
# you can also create a list by importing numpy module
import numpy as np

# save two lists of 100 integers from 1  to 10
a = (list(np.random.randint(low = 1,high=10,size=100)))
b = (list(np.random.randint(low = 1,high=10,size=100)))

In [199]:
print (a)
print ("----")
print (b)

[7, 3, 7, 4, 1, 9, 9, 2, 9, 4, 5, 1, 2, 4, 1, 2, 2, 7, 5, 1, 8, 2, 7, 3, 8, 3, 4, 8, 8, 6, 5, 3, 4, 3, 2, 4, 7, 9, 5, 9, 5, 1, 3, 5, 7, 5, 6, 6, 4, 6, 4, 2, 7, 3, 1, 7, 2, 7, 4, 3, 2, 2, 8, 3, 3, 7, 5, 6, 6, 9, 6, 8, 3, 4, 4, 2, 8, 8, 4, 5, 8, 4, 2, 7, 7, 6, 6, 1, 3, 1, 1, 9, 1, 7, 6, 9, 3, 4, 2, 7]
----
[6, 3, 3, 3, 3, 5, 4, 3, 9, 4, 4, 1, 8, 3, 1, 8, 8, 3, 1, 2, 2, 6, 5, 3, 4, 3, 7, 4, 9, 6, 5, 1, 5, 5, 4, 3, 8, 1, 7, 4, 8, 3, 5, 1, 7, 1, 2, 7, 9, 9, 8, 1, 6, 4, 8, 9, 4, 2, 8, 9, 4, 8, 3, 8, 5, 8, 3, 2, 6, 8, 6, 6, 5, 5, 8, 2, 3, 9, 5, 9, 6, 1, 7, 5, 8, 9, 2, 3, 8, 4, 3, 9, 5, 3, 2, 4, 4, 7, 3, 6]


In [200]:
type(a)

list

In [201]:
type (b)

list

The data structure of a list is different than that of a vector although they look to be the same.

In [203]:
# now lets convert a list to a vector!
# already imported numpy as np 

vctr_a = np.array(a) 
vctr_b = np.array(b)

print("Vectors created from a lists:", vctr_a,"---", vctr_b) 


Vector created from a list: [7 3 7 4 1 9 9 2 9 4 5 1 2 4 1 2 2 7 5 1 8 2 7 3 8 3 4 8 8 6 5 3 4 3 2 4 7
 9 5 9 5 1 3 5 7 5 6 6 4 6 4 2 7 3 1 7 2 7 4 3 2 2 8 3 3 7 5 6 6 9 6 8 3 4
 4 2 8 8 4 5 8 4 2 7 7 6 6 1 3 1 1 9 1 7 6 9 3 4 2 7] --- [6 3 3 3 3 5 4 3 9 4 4 1 8 3 1 8 8 3 1 2 2 6 5 3 4 3 7 4 9 6 5 1 5 5 4 3 8
 1 7 4 8 3 5 1 7 1 2 7 9 9 8 1 6 4 8 9 4 2 8 9 4 8 3 8 5 8 3 2 6 8 6 6 5 5
 8 2 3 9 5 9 6 1 7 5 8 9 2 3 8 4 3 9 5 3 2 4 4 7 3 6]


## At the core of the NumPy package, is the ndarray object.

In [21]:
# here is a way to create an ndarray
# generates list of 4 float values
print(np.random.random_sample(size = 4))

[0.41970099 0.73452929 0.61229997 0.56060761]


In [50]:
# generates 2d list of 4*4
e = (np.random.random_sample(size = (4,4)))
type(e)

numpy.ndarray

In [49]:
# generates 2d list of 4*4
f = (np.random.random_sample(size = (4,4)))
type(f)

numpy.ndarray

In [17]:
# multiply two integer ndarrays
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])

This produces the correct answer, but if a and b each contain millions of numbers, we will pay the price for the inefficiencies of looping in Python. We could accomplish the same task much more quickly in C by writing (for clarity we neglect variable declarations and initializations, memory allocation, etc.)

```c
for (i = 0; i < rows; i++): {
  c[i] = a[i]*b[i];
}
```
This saves all the overhead involved in interpreting the Python code and manipulating Python objects, but at the expense of the benefits gained from coding in Python. Furthermore, the coding work required increases with the dimensionality of our data. In the case of a 2-D array, for example, the C code (abridged as before) expands to

```c
for (i = 0; i < rows; i++): {
  for (j = 0; j < columns; j++): {
    c[i][j] = a[i][j]*b[i][j];
  }
}
```

NumPy gives us the best of both worlds: element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. In NumPy

In [31]:
g = e * f
print(g)

[[0.71865002 0.1217977  0.43251094 0.12521445]
 [0.02245344 0.45979811 0.53650348 0.13454848]
 [0.1224389  0.03564147 0.31175429 0.13521226]
 [0.13691859 0.01028804 0.19809876 0.35967559]]


does what the earlier examples do, at near-C speeds, but with the code simplicity we expect from something based on Python. Indeed, the NumPy idiom is even simpler! This last example illustrates two of NumPy’s features which are the basis of much of its power: vectorization and broadcasting.

## The Basics
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

```numpy
[[1., 0., 0.],
 [0., 1., 2.]]
```

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

**ndarray.ndim**
the number of axes (dimensions) of the array.

**ndarray.shape**
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**
the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [33]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
a.shape

(3, 5)

In [35]:
a.ndim

2

In [36]:
a.dtype.name

'int64'

In [37]:
a.itemsize

8

In [38]:
a.size

15

In [39]:
type(a)

numpy.ndarray

In [41]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [42]:
type(b)

numpy.ndarray

## Array Creation
There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [45]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [46]:
a.dtype

dtype('int64')

In [47]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [51]:
a = np.array(1, 2, 3, 4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [60]:
a = np.array([1, 2, 3, 4])  # RIGHT
a

array([1, 2, 3, 4])

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [58]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [59]:
x  = np.array([(1.5, 2, 3), (4, 5, 6), (7, 8, 9)])
x

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [61]:
y  = np.array([(1.5, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12)])
y

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10. , 11. , 12. ]])

In [62]:
z  = np.array([(1.5, 2, 3), (4, 5, 6), (7, 8, 9), (10, 11, 12), (13, 14, 15)])
z

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10. , 11. , 12. ],
       [13. , 14. , 15. ]])

The type of the array can also be explicitly specified at creation time:

In [63]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

In [64]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [66]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [67]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [68]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [99]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [100]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [73]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

## Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

the last axis is printed from left to right,

the second-to-last is printed from top to bottom,

the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [74]:
a = np.arange(6)                    # 1d array
print(a)

[0 1 2 3 4 5]


In [75]:
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [76]:
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [77]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [78]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [79]:
import sys
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

In [81]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

## Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [82]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [83]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [84]:
# subtract a from b
c = a - b
c

array([20, 29, 38, 47])

In [88]:
#raise b to the power of 2
b**2

array([0, 1, 4, 9])

In [86]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [87]:
a < 35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [89]:
A = np.array([[1, 1],
              [0, 1]])

In [90]:
B = np.array([[2, 0],
              [3, 4]])

In [91]:
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [92]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [93]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [94]:
rg = np.random.default_rng(1)  # create instance of default random number generator

In [95]:
a = np.ones((2, 3), dtype=int)

In [96]:
b = rg.random((2, 3))

In [97]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [98]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [101]:
a = np.ones(3, dtype=np.int32)

In [102]:
b = np.linspace(0, pi, 3)

In [103]:
b.dtype.name

'float64'

In [104]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [105]:
c.dtype.name

'float64'

In [107]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [108]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [109]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [110]:
print(a.sum())
print(a.min())
print(a.max())

3.1057109529998157
0.027559113243068367
0.8277025938204418


By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [111]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
print(b.sum(axis=0))     # sum of each column

[12 15 18 21]


In [114]:
print(b.min(axis=1))     # min of each row

[0 4 8]


In [115]:
print(b.cumsum(axis=1))  # cumulative sum along each row

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [116]:
B = np.arange(3)
B

array([0, 1, 2])

In [117]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [118]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [119]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

## Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [121]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [122]:
a[2]

8

In [123]:
a[2:5]

array([ 8, 27, 64])

In [124]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [126]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [127]:
for i in a:
     print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [128]:
def f(x, y):
     return 10 * x + y

In [129]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [130]:
b[2, 3]

23

In [131]:
b[0:5, 1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [132]:
b[:, 1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [133]:
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [134]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i, ...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

```numpy
x[1, 2, ...] is equivalent to x[1, 2, :, :, :],

x[..., 3] to x[:, :, :, :, 3] and

x[4, ..., 5, :] to x[4, :, :, 5, :].
```

In [135]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100, 101, 102],
                [110, 112, 113]]])

In [136]:
c.shape

(2, 2, 3)

In [137]:
c[1, ...]  # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [138]:
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [139]:
for row in b:
     print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [140]:
for element in b.flat:
     print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Shape Manipulation
Changing the shape of an array
An array has a shape given by the number of elements along each axis:

In [142]:
a = np.floor(10 * rg.random((3, 4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [143]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [144]:
a.ravel()  # returns the array, flattened

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [145]:
a.reshape(6, 2)  # returns the array with a modified shape

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [146]:
a.T  # returns the array, transposed

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [147]:
a.T.shape

(4, 3)

In [148]:
a.shape

(3, 4)

The order of the elements in the array resulting from ravel is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0, 0] is a[0, 1]. If the array is reshaped to some other shape, again the array is treated as “C-style”. NumPy normally creates arrays stored in this order, so ravel will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel and reshape can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [149]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [150]:
a.resize((2, 6))
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [151]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

## Stacking together different arrays
Several arrays can be stacked together along different axes:

In [153]:
a = np.floor(10 * rg.random((2, 2)))
a

array([[9., 7.],
       [5., 2.]])

In [154]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[1., 9.],
       [5., 1.]])

In [155]:
np.vstack((a, b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [156]:
np.hstack((a, b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [157]:
from numpy import newaxis
np.column_stack((a, b))  # with 2D arrays

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [158]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b))  # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [159]:
np.hstack((a, b))        # the result is different

array([4., 2., 3., 8.])

In [160]:
a[:, newaxis]  # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [161]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [162]:
np.hstack((a[:, newaxis], b[:, newaxis]))  # the result is the same

array([[4., 3.],
       [2., 8.]])

On the other hand, the function row_stack is equivalent to vstack for any input arrays. In fact, row_stack is an alias for vstack:

In [163]:
np.column_stack is np.hstack

False

In [164]:
np.row_stack is np.vstack

True

In general, for arrays with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

Note

In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals :.



In [165]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

When used with arrays as arguments, r_ and c_ are similar to vstack and hstack in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate.

## Splitting one array into several smaller ones
Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [166]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [167]:
# Split `a` into 3
np.hsplit(a, 3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [168]:
# Split `a` after the third and the fourth column
np.hsplit(a, (3, 4))

[array([[6., 7., 6.],
        [8., 5., 5.]]),
 array([[9.],
        [7.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2.],
        [1., 8., 6., 7., 1., 8., 1., 0.]])]

vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.

## Copies and Views
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

### No Copy at All
Simple assignments make no copy of objects or their data.

In [169]:
 a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [170]:
b = a            # no new object is created

In [171]:
b is a           # a and b are two names for the same ndarray object

True

Python passes mutable objects as references, so function calls make no copy.

In [172]:
def f(x):
    print(id(x))

In [173]:
id(a)  # id is a unique identifier of an object

4395763392

In [174]:
f(a) # may vary

4395763392


### View or Shallow Copy
Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [175]:
c = a.view()
c is a

False

In [176]:
c.base is a            # c is a view of the data owned by a

True

In [177]:
c.flags.owndata

False

In [178]:
c = c.reshape((2, 6))  # a's shape doesn't change
a.shape

(3, 4)

In [181]:
c[0, 4] = 1234         # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:

In [184]:
s = a[:, 1:3]
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### Deep Copy
The copy method makes a complete copy of the array and its data.

In [186]:
d = a.copy()  # a new array object with new data is created
d is a

False

In [187]:
d.base is a  # d doesn't share anything with a

False

In [188]:
d[0, 0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Sometimes copy should be called after slicing if the original array is not required anymore. For example, suppose a is a huge intermediate result and the final result b only contains a small fraction of a, a deep copy should be made when constructing b with slicing:

In [189]:
a = np.arange(int(1e8))
b = a[:100].copy()

In [190]:
del a  # the memory of ``a`` can be released.

## Functions and Methods Overview
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

### Array Creation
[arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange), [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array), [copy](https://numpy.org/doc/stable/reference/generated/numpy.copy.html#numpy.copy), [empty](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty), [empty_like](https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html#numpy.empty_like), [eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye), [fromfile](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html#numpy.fromfile), [fromfunction](https://numpy.org/doc/stable/reference/generated/numpy.fromfunction.html#numpy.fromfunction), [identity](https://numpy.org/doc/stable/reference/generated/numpy.identity.html#numpy.identity), [linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace), [logspace](https://numpy.org/doc/stable/reference/generated/numpy.logspace.html#numpy.logspace), [mgrid](https://numpy.org/doc/stable/reference/generated/numpy.mgrid.html#numpy.mgrid), [ogrid](https://numpy.org/doc/stable/reference/generated/numpy.ogrid.html#numpy.ogrid), [ones](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones), [ones_like](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like), [r_](https://numpy.org/doc/stable/reference/generated/numpy.r_.html#numpy.r_), [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), [zeros_like](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html#numpy.zeros_like)

### Conversions
[ndarray.astype](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html#numpy.ndarray.astype), [atleast_1d](https://numpy.org/doc/stable/reference/generated/numpy.atleast_1d.html#numpy.atleast_1d), [atleast_2d](https://numpy.org/doc/stable/reference/generated/numpy.atleast_2d.html#numpy.atleast_2d), [atleast_3d](https://numpy.org/doc/stable/reference/generated/numpy.atleast_3d.html#numpy.atleast_3d), [mat](https://numpy.org/doc/stable/reference/generated/numpy.mat.html#numpy.mat)

### Manipulations
[array_split](https://numpy.org/doc/stable/reference/generated/numpy.array_split.html#numpy.array_split), [column_stack](https://numpy.org/doc/stable/reference/generated/numpy.column_stack.html#numpy.column_stack), [concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate), [diagonal](https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html#numpy.diagonal), [dsplit](https://numpy.org/doc/stable/reference/generated/numpy.dsplit.html#numpy.dsplit), [dstack](https://numpy.org/doc/stable/reference/generated/numpy.dstack.html#numpy.dstack), [hsplit](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html#numpy.hsplit), [hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html#numpy.hstack), [ndarray.item](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.item.html#numpy.ndarray.item), [newaxis](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis), [ravel](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html#numpy.ravel), [repeat](https://numpy.org/doc/stable/reference/generated/numpy.repeat.html#numpy.repeat), [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape), [resize](https://numpy.org/doc/stable/reference/generated/numpy.resize.html#numpy.resize), [squeeze](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html#numpy.squeeze), [swapaxes](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html#numpy.swapaxes), [take](https://numpy.org/doc/stable/reference/generated/numpy.take.html#numpy.take), [transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html#numpy.transpose), [vsplit](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html#numpy.vsplit), [vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack)

### Questions
[all](https://numpy.org/doc/stable/reference/generated/numpy.all.html#numpy.all), [any](https://numpy.org/doc/stable/reference/generated/numpy.any.html#numpy.any), [nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html#numpy.nonzero), [where](https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where)

### Ordering
[argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html#numpy.argmax), [argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#numpy.argmin), [argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#numpy.argsort), [max](https://docs.python.org/dev/library/functions.html#max), [min](https://docs.python.org/dev/library/functions.html#min), [ptp](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html#numpy.ptp), [searchsorted](https://numpy.org/doc/stable/reference/generated/numpy.searchsorted.html#numpy.searchsorted), [sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort)

### Operations
[choose](https://numpy.org/doc/stable/reference/generated/numpy.choose.html#numpy.choose), [compress](https://numpy.org/doc/stable/reference/generated/numpy.compress.html#numpy.compress), [cumprod](https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html#numpy.cumprod), [cumsum](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html#numpy.cumsum), [inner](https://numpy.org/doc/stable/reference/generated/numpy.inner.html#numpy.inner), [ndarray.fill](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.fill.html#numpy.ndarray.fill), [imag](https://numpy.org/doc/stable/reference/generated/numpy.imag.html#numpy.imag), [prod](https://numpy.org/doc/stable/reference/generated/numpy.prod.html#numpy.prod), [put](https://numpy.org/doc/stable/reference/generated/numpy.put.html#numpy.put), [putmask](https://numpy.org/doc/stable/reference/generated/numpy.putmask.html#numpy.putmask), [real](https://numpy.org/doc/stable/reference/generated/numpy.real.html#numpy.real), [sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html#numpy.sum)

### Basic Statistics
[cov](https://numpy.org/doc/stable/reference/generated/numpy.cov.html#numpy.cov), [mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html#numpy.mean), [std](https://numpy.org/doc/stable/reference/generated/numpy.std.html#numpy.std), [var](https://numpy.org/doc/stable/reference/generated/numpy.var.html#numpy.var)

### Basic Linear Algebra
[cross](https://numpy.org/doc/stable/reference/generated/numpy.cross.html#numpy.cross), [dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy.dot), [outer](https://numpy.org/doc/stable/reference/generated/numpy.outer.html#numpy.outer), [linalg.svd](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html#numpy.linalg.svd), [vdot](https://numpy.org/doc/stable/reference/generated/numpy.vdot.html#numpy.vdot)