<img src="https://numpy.org/doc/stable/_static/numpylogo.svg" align="left" alt="Python image" width = "300">

# Linear Algebra Basics using Numpy

- [Jason Brownlee's Linear Algebra Cheat Sheet for Machine Learning](https://machinelearningmastery.com/linear-algebra-cheat-sheet-for-machine-learning/)
- [Ivan Savov's Linear algebra explained in four pages](https://minireference.com/static/tutorials/linear_algebra_in_4_pages.pdf)
- [Numpy Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)
- [Numpy Statistics](https://numpy.org/doc/stable/reference/routines.statistics.html)
- [Linear Algebra Cheet Sheet](https://github.com/scalanlp/breeze/wiki/Linear-Algebra-Cheat-Sheet)


## 1. Arrays
There are many ways to create NumPy arrays.

In [5]:
# Array
from numpy import array
A = array([[1,2,3],[1,2,3],[1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
# Empty
from numpy import empty
B = empty([3,3])
B

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [4.9e-324, 9.9e-324, 1.5e-323],
       [4.9e-324, 9.9e-324, 1.5e-323]])

In [7]:
# Zeros
from numpy import zeros
C = zeros([3,5])
C

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
from numpy import ones
D = ones([5, 5])
D

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 2. Vectors
A vector is a list or column of scalars.

In [19]:
# Create a simple list in Python

a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(type(a))
print(type(b))

<class 'list'>
<class 'list'>


In [20]:
import numpy as np
# convert the list to vectors
vctr_a = np.array(a) 
vctr_b = np.array(b)
print(type(vctr_a))
print(type(vctr_b))
print("you'll notice that lists and vectors are really a 1 dimensional array")

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
you'll notice that lists and vectors are really a 1 dimensional array


In [21]:
# list Addition
print (a)
print ("---")
print (b)
print ("---")
c = a + b
print(c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
---
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
---
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [22]:
# vector Addition
print (vctr_a)
print ("---")
print (vctr_b)
print ("---")
vctr_c = vctr_a + vctr_b
print(vctr_c)

[0 1 2 3 4 5 6 7 8 9]
---
[0 1 2 3 4 5 6 7 8 9]
---
[ 0  2  4  6  8 10 12 14 16 18]


## What do you notice with the difference between lists and vectors?

1. commas... 
2. by adding the two lists together it just Python just appended b onto a.
3. with vectors the "+" actually ran addition on each variable in the vector/ndarray

In [23]:
# list Subtraction and you'll notice this won't work, and neither will the rest of the mathematical operators
c = a - b
print (c)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [24]:
# Vector Subtraction
print (vctr_a)
print ("---")
print (vctr_b)
print ("---")
vctr_c = vctr_a - vctr_b
print(vctr_c)

[0 1 2 3 4 5 6 7 8 9]
---
[0 1 2 3 4 5 6 7 8 9]
---
[0 0 0 0 0 0 0 0 0 0]


In [25]:
# Vector Multiplication
print (vctr_a)
print ("---")
print (vctr_b)
print ("---")
vctr_c = vctr_a * vctr_b
print(vctr_c)

[0 1 2 3 4 5 6 7 8 9]
---
[0 1 2 3 4 5 6 7 8 9]
---
[ 0  1  4  9 16 25 36 49 64 81]


In [26]:
# Vector Division notice can't divide by zero
print (vctr_a)
print ("---")
print (vctr_b)
print ("---")
vctr_c = vctr_a / vctr_b
print(vctr_c)

[0 1 2 3 4 5 6 7 8 9]
---
[0 1 2 3 4 5 6 7 8 9]
---
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/var/folders/wk/6why77bn1kn0l0pkd4vd3zl00000gn/T/ipykernel_79097/1311159810.py:6: RuntimeWarning: invalid value encountered in true_divide
  vctr_c = vctr_a / vctr_b


In [28]:
# Vector Dot Product
vctr_c = vctr_a.dot(vctr_b)
print (vctr_c)

285


In [29]:
vctr_c = vctr_a @ vctr_b
print (vctr_c)

285


In [31]:
# Vector-Scalar Multiplication
print (vctr_a)
print ("---")
vctr_c = vctr_a * 2.2
print(vctr_c)

[0 1 2 3 4 5 6 7 8 9]
---
[ 0.   2.2  4.4  6.6  8.8 11.  13.2 15.4 17.6 19.8]


In [32]:
# Vector Norm
from numpy.linalg import norm
l2 = norm(vctr_c)
print(l2)

37.14027463549509


## 3. Matrices
A matrix is a two-dimensional array of scalars.

Matrix Addition


In [92]:
#A = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])

A = np.matrix('1 2; 3 4')
A

matrix([[1, 2],
        [3, 4]])

In [93]:
print(A)

[[1 2]
 [3 4]]


In [94]:
B = np.matrix('1 2; 3 4')
B

matrix([[1, 2],
        [3, 4]])

In [95]:
print(B)

[[1 2]
 [3 4]]


In [96]:
# Matrix Addition
C = A + B
print(C)

[[2 4]
 [6 8]]


In [97]:
# Matrix Subtraction
C = A - B
print(C)

[[0 0]
 [0 0]]


In [98]:
# Matrix Multiplication (Hadamard Product)
C = A * B
print(C)

[[ 7 10]
 [15 22]]


In [99]:
# Matrix Division 
C = A / B
print(C)

[[1. 1.]
 [1. 1.]]


In [100]:
# Matrix-Matrix Multiplication (Dot Product)
C = A.dot(B)
print(C)

[[ 7 10]
 [15 22]]


In [101]:
#hmmm what is going on here?
print(A.ndim)
print(B.ndim)
print(C.ndim)

2
2
2


In [102]:
print(A.size)
print(B.size)
print(C.size)

4
4
4


In [103]:
print(A.shape)
print(B.shape)
print(C.shape)

(2, 2)
(2, 2)
(2, 2)


In [104]:
print(type(A))

<class 'numpy.matrix'>


In [112]:
# Matrix-Vector Multiplication (Dot Product)
b = np.array([[1, 2],[3, 4]])
C = A.dot(b)
C
# or another way
C = A @ b
C

matrix([[ 7, 10],
        [15, 22]])

In [111]:
# Matrix-Scalar Multiplication
C = A.dot(2.2)
C
# or another way 
C = A * 2.2
C

matrix([[2.2, 4.4],
        [6.6, 8.8]])

## 4. Types of Matrices
Different types of matrices are often used as elements in broader calculations.

In [116]:
# Triangle Matrix
# lower
from numpy import tril
lower = tril(A)
lower

array([[1, 0],
       [3, 4]])

In [118]:
# upper
from numpy import triu
upper = triu(A)
upper

array([[1, 2],
       [0, 4]])

In [120]:
# Diagonal Matrix
from numpy import diag
d = diag(A)
d

array([1, 4])

In [121]:
A

matrix([[1, 2],
        [3, 4]])

In [123]:
# Identity Matrix
from numpy import eye
I = eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5. Matrix Operations
Matrix operations are often used as elements in broader calculations.

In [125]:
# Matrix Transpose
B = A.T
B

matrix([[1, 3],
        [2, 4]])

In [126]:
# Matrix Inversion
from numpy.linalg import inv
B = inv(A)
B

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [127]:
# Matrix Trace
from numpy import trace
B = trace(A)
B

5

In [128]:
# Matrix Rank
from numpy.linalg import matrix_rank
r = matrix_rank(A)
r

2

## 6. Matrix Factorization
Matrix factorization, or matrix decomposition, breaks a matrix down into its constituent parts to make other operations simpler and more numerically stable.

In [130]:
# LU Decomposition
from scipy.linalg import lu
P, L, U = lu(A)
print(P, L, U)

[[0. 1.]
 [1. 0.]] [[1.         0.        ]
 [0.33333333 1.        ]] [[3.         4.        ]
 [0.         0.66666667]]


In [131]:
# QR Decomposition
from numpy.linalg import qr
Q, R = qr(A, 'complete')
print (Q, R)

[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]] [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [132]:
# Eigendecomposition
from numpy.linalg import eig
values, vectors = eig(A)
print(values, vectors)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [133]:
# Singular-Value Decomposition
from scipy.linalg import svd
U, s, V = svd(A)
print(U,s,V)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] [5.4649857  0.36596619] [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


## 7. Statistics
Statistics summarize the contents of vectors or matrices and are often used as components in broader operations.

In [135]:
# Mean
from numpy import mean
result = mean(b)
print(result)

2.5


In [137]:
# Variance
from numpy import var
result = var(b, ddof=1)
print(result)

1.6666666666666667


In [138]:
# Standard Deviation
from numpy import std
result = std(b, ddof=1)
print(result)

1.2909944487358056


In [140]:
# Covariance Matrix
from numpy import cov
sigma = cov(vctr_a, vctr_b)
print(sigma)

[[9.16666667 9.16666667]
 [9.16666667 9.16666667]]


In [146]:
# Linear Least Squares
a = np.array([[1, 2],[3, 4]])
b = np.array([[1, 2],[3, 4]])
from numpy.linalg import lstsq
c = lstsq(a, b, rcond=None)
print (c)

(array([[ 1.00000000e+00,  3.00928583e-16],
       [-4.01238111e-16,  1.00000000e+00]]), array([], dtype=float64), 2, array([5.4649857 , 0.36596619]))
