# Introduction to R

In [4]:
install.packages("vembedr")
library("vembedr")
embed_vimeo("715793781")


The downloaded binary packages are in
	/var/folders/wk/6why77bn1kn0l0pkd4vd3zl00000gn/T//RtmptQWmUI/downloaded_packages


Shiny tags cannot be represented in plain text (need html)

https://vimeo.com/715793781

### Table of Contents <a class="anchor" id="DS102L1-WS.5_toc"></a>

* [Table of Contents](#DS102L1-WS.5_toc)
    * [Page 1 - The R application is an interactive R interpreter](#DS102L1-WS.5_page_1)
    * [Page 2 - Help](#DS102L1-WS.5_page_2)
    * [Page 3 - Vectors](#DS102L1-WS.5_page_3)
    * [Page 4 - Subsetting](#DS102L1-WS.5_page_4)
    * [Page 5 - Vectorized functions](#DS102L1-WS.5_page_5)
    * [Page 6 - Recycling](#DS102L1-WS.5_page_6)
    * [Page 7 - Functions](#DS102L1-WS.5_page_7)
    * [Page 8 - Matrices](#DS102L1-WS.5_page_8)
    * [Page 9 - Loading data into R](#DS102L1-WS.5_page_9)
    * [Page 10 - Working with Packages](#DS102L1-WS.5_page_10)
    * [Page 11 - Summary](#DS102L1-WS.5_page_11)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 1 - The R application is an interactive R interpreter <a class="anchor" id="DS102L1-WS.5_page_1"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


Basically any line starting with a **>** character is R asking for input. 

If you see a **+** prompt, it means that you didn't finish typing a statement at the R prompt and R is asking you to provide the rest of the expression. 

Hitting the return key will send your input to R to be evaluated. 

R's response is then spit back at you in the line immediately following your input, after which R asks for more input. 

This is called a **REPL (Read-Evaluate-Print-Loop)**. 

It is also possible for R to read a batch of commands saved in a file called **batch mode**. 

As you might imagine, R supports most of all mathematical operators as with most other languages.

<p style="text-align: center">
  <img  src="../../../Media/R-Terminal.png" width="600" alt="R-Terminal">
</p>

If you path is set for R, then you'll be able to just type R in a terminal. The above example is on a MacOS.

Another way to start R is by double click R application shown below

<p style="text-align: center">
  <img  src="../../../Media/R-Application-Icon.png" width="100" alt="R-App-Icon">
</p>

This in turn opens an R console application

<p style="text-align: center">
  <img  src="../../../Media/R-Console.png" width="600" alt="R-App">
</p>

Another way to interact with R is through the RStudio Application, yet another way, but this application is a little more feature rich.

<p style="text-align: center">
  <img  src="../../../Media/RStudio-Icon.png" width="100" alt="R-Studio-Icon">
</p>

<p style="text-align: center">
  <img  src="../../../Media/RStudio.png" width="800" alt="R-Studio">
</p>

Lastly, you can create an R notebook in Jupyter Lab if you have follow the instructions correctly in our Homebrew or Chocolatey instructions.

<p style="text-align: center">
  <img  src="../../../Media/Jupyter-R-Kernel.png" width="800" alt="Jupyter-R">
</p>

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 2 - Help <a class="anchor" id="DS102L1-WS.5_page_2"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

Okay, we've covered some of the ways we can run R instructions. Let's next go over how we can obtain help.

## HELP!

There is a nice Help function contained in the R language and you can get help on any other function by running one of two commands:

```r
help(function)
?function
```

let's try it out "gsub" which is a function to conduct Pattern Matching and Replacement

In [5]:
help(gsub)

grep                   package:base                    R Documentation

_P_a_t_t_e_r_n _M_a_t_c_h_i_n_g _a_n_d _R_e_p_l_a_c_e_m_e_n_t

_D_e_s_c_r_i_p_t_i_o_n:

     ‘grep’, ‘grepl’, ‘regexpr’, ‘gregexpr’, ‘regexec’ and ‘gregexec’
     search for matches to argument ‘pattern’ within each element of a
     character vector: they differ in the format of and amount of
     detail in the results.

     ‘sub’ and ‘gsub’ perform replacement of the first and all matches
     respectively.

_U_s_a_g_e:

     grep(pattern, x, ignore.case = FALSE, perl = FALSE, value = FALSE,
          fixed = FALSE, useBytes = FALSE, invert = FALSE)
     
     grepl(pattern, x, ignore.case = FALSE, perl = FALSE,
           fixed = FALSE, useBytes = FALSE)
     
     sub(pattern, replacement, x, ignore.case = FALSE, perl = FALSE,
         fixed = FALSE, useBytes = FALSE)
     
     gsub(pattern, replacement, x, ignore.case = FALSE, perl = FALSE,
          fixed = FALSE, useBytes = FALSE)
     
     regexpr(pattern, text, ignore.case = FALSE, perl = FALSE,
             fixed = FALSE, useBytes = FALSE)
     
     gregexpr(pattern, text, ignore.case = FALSE, perl = FALSE,
              fixed = FALSE, useBytes = FALSE)
     
     regexec(pattern, text, ignore.case = FALSE, perl = FALSE,
             fixed = FALSE, useBytes = FALSE)
     
     gregexec(pattern, text, ignore.case = FALSE, perl = FALSE,
             fixed = FALSE, useBytes = FALSE)
     
_A_r_g_u_m_e_n_t_s:

 pattern: character string containing a regular expression (or
          character string for ‘fixed = TRUE’) to be matched in the
          given character vector.  Coerced by ‘as.character’ to a
          character string if possible.  If a character vector of
          length 2 or more is supplied, the first element is used with
          a warning.  Missing values are allowed except for ‘regexpr’,
          ‘gregexpr’ and ‘regexec’.

 x, text: a character vector where matches are sought, or an object
          which can be coerced by ‘as.character’ to a character vector.
          Long vectors are supported.

ignore.case: if ‘FALSE’, the pattern matching is _case sensitive_ and
          if ‘TRUE’, case is ignored during matching.

    perl: logical.  Should Perl-compatible regexps be used?

   value: if ‘FALSE’, a vector containing the (‘integer’) indices of
          the matches determined by ‘grep’ is returned, and if ‘TRUE’,
          a vector containing the matching elements themselves is
          returned.

   fixed: logical.  If ‘TRUE’, ‘pattern’ is a string to be matched as
          is.  Overrides all conflicting arguments.

useBytes: logical.  If ‘TRUE’ the matching is done byte-by-byte rather
          than character-by-character.  See ‘Details’.

  invert: logical.  If ‘TRUE’ return indices or values for elements
          that do _not_ match.

replacement: a replacement for matched pattern in ‘sub’ and ‘gsub’.
          Coerced to character if possible.  For ‘fixed = FALSE’ this
          can include backreferences ‘"\1"’ to ‘"\9"’ to parenthesized
          subexpressions of ‘pattern’.  For ‘perl = TRUE’ only, it can
          also contain ‘"\U"’ or ‘"\L"’ to convert the rest of the
          replacement to upper or lower case and ‘"\E"’ to end case
          conversion.  If a character vector of length 2 or more is
          supplied, the first element is used with a warning.  If ‘NA’,
          all elements in the result corresponding to matches will be
          set to ‘NA’.

_D_e_t_a_i_l_s:

     Arguments which should be character strings or character vectors
     are coerced to character if possible.

     Each of these functions operates in one of three modes:

       1. ‘fixed = TRUE’: use exact matching.

       2. ‘perl = TRUE’: use Perl-style regular expressions.

       3. ‘fixed = FALSE, perl = FALSE’: use POSIX 1003.2 extended
          regular expressions (the default).

     See the help pages on

A lot of times, you won't remember the exact name of a function, but you'll have sort of an idea in your memory. For this, you can use the help.search() function:

```r

help.search(ggpl)

??ggpl
```


In [6]:
??ggpl

R Information

Vignettes with name or keyword or title matching ‘ggpl’ using regular
expression matching:


ggbeeswarm::usageExamples
                        vipor package usage examples
  Concepts: ggplot, ggplot2
ggplot2::extending-ggplot2
                        Extending ggplot2
ggplot2::ggplot2-in-packages
                        Using ggplot2 in packages
ggplot2::ggplot2-specs
                        Aesthetic specifications


Type 'vignette("FOO", package="PKG")' to inspect entries 'PKG::FOO'.



Demos with name or title matching ‘ggpl’ using regular expression
matching:


crs::ggplot_cos         R code for plotting a model with one numeric
                        and one factor predictor using ggplot2
microplot::boxplot-ggplot
                        A column of box plots, one for each row of
                        summary data. This demo uses ggplot2, latex and
                        MS Word.
microplot::HowToUseMicroplot
                        Simple to complex examples usi

In [7]:
# if you want a little bit of light reading try 
# ??statistics

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 3 - Vectors <a class="anchor" id="DS102L1-WS.5_page_3"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

Vectors are the most basic data structures in R, and they are ubiquitous indeed. In fact, even the single values that we've been working with thus far were actually vectors of length 1. 

Vectors are essentially an ordered collection of values of the same atomic data type. Vectors can be arbitrarily large (with some limitations) or they can be just one single value.

The canonical way of building vectors manually is using the c() function (which stands for combine):

In [8]:
phone.number.vector <- c(5, 5, 5, 1, 2, 1, 2) 

In [9]:
phone.number.vector

[1] 5 5 5 1 2 1 2

We've created a phone number with just numbers

Let's add a hyphen

In [10]:
phone.number.vector2 <- c(5, 5, 5, "-", 1, 2, 1, 2) 

In [11]:
phone.number.vector2

[1] "5" "5" "5" "-" "1" "2" "1" "2"

Notice the single quotes now as R converts all the items in the vector (called elements) into character data types to satisfy the condition that all elements of a vector must be of the same type.

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 4 - Subsetting <a class="anchor" id="DS102L1-WS.5_page_4"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

It is very common to want to extract one or more elements from a vector. For this, we use a technique called indexing or subsetting. After the vector, we put an integer in square brackets ```([])``` called the subscript operator. This instructs R to return the element at that index.

In [12]:
phone.number.vector[5]

[1] 2

In [13]:
phone.number.vector[1:7]

[1] 5 5 5 1 2 1 2

Look what happens when we try to index outside of the vector

In [14]:
phone.number.vector[8]

[1] NA

Let's extract the first, third, fifth, and seventh element from our vector 

In [15]:
phone.number.vector[c(1,3,5,7)]

[1] 5 5 2 2

The ability to use vectors to index other vectors may not seem like much now, but its usefulness will become clear soon.

Another way to create vectors is using sequences:

In [16]:
new.vector <- 1:10 

In [17]:
new.vector

[1]  1  2  3  4  5  6  7  8  9 10

In [18]:
decrement.50.30.by2.vector <- seq(50, 30, by=-2)

In [19]:
decrement.50.30.by2.vector 

[1] 50 48 46 44 42 40 38 36 34 32 30

In [20]:
?seq

seq                    package:base                    R Documentation

_S_e_q_u_e_n_c_e _G_e_n_e_r_a_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Generate regular sequences.  ‘seq’ is a standard generic with a
     default method.  ‘seq.int’ is a primitive which can be much faster
     but has a few restrictions.  ‘seq_along’ and ‘seq_len’ are very
     fast primitives for two common cases.

_U_s_a_g_e:

     seq(...)
     
     ## Default S3 method:
     seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)),
         length.out = NULL, along.with = NULL, ...)
     
     seq.int(from, to, by, length.out, along.with, ...)
     
     seq_along(along.with)
     seq_len(length.out)
     
_A_r_g_u_m_e_n_t_s:

     ...: arguments passed to or from methods.

from, to: the starting and (maximal) end values of the sequence.  Of
          length ‘1’ unless just ‘from’ is supplied as an unnamed
          argument.

      by: number: increment of the sequence.

length.out: desired length of the sequence.  A non-negative number,
          which for ‘seq’ and ‘seq.int’ will be rounded up if
          fractional.

along.with: take the length from the length of this argument.

_D_e_t_a_i_l_s:

     Numerical inputs should all be finite (that is, not infinite,
     ‘NaN’ or ‘NA’).

     The interpretation of the unnamed arguments of ‘seq’ and ‘seq.int’
     is _not_ standard, and it is recommended always to name the
     arguments when programming.

     ‘seq’ is generic, and only the default method is described here.
     Note that it dispatches on the class of the *first* argument
     irrespective of argument names.  This can have unintended
     consequences if it is called with just one argument intending this
     to be taken as ‘along.with’: it is much better to use ‘seq_along’
     in that case.

     ‘seq.int’ is an internal generic which dispatches on methods for
     ‘"seq"’ based on the class of the first supplied argument (before
     argument matching).

     Typical usages are

     seq(from, to)
     seq(from, to, by= )
     seq(from, to, length.out= )
     seq(along.with= )
     seq(from)
     seq(length.out= )
     
     The first form generates the sequence ‘from, from+/-1, ..., to’
     (identical to ‘from:to’).

     The second form generates ‘from, from+by’, ..., up to the sequence
     value less than or equal to ‘to’.  Specifying ‘to - from’ and ‘by’
     of opposite signs is an error.  Note that the computed final value
     can go just beyond ‘to’ to allow for rounding error, but is
     truncated to ‘to’.  (‘Just beyond’ is by up to 1e-10 times
     ‘abs(from - to)’.)

     The third generates a sequence of ‘length.out’ equally spaced
     values from ‘from’ to ‘to’.  (‘length.out’ is usually abbreviated
     to ‘length’ or ‘len’, and ‘seq_len’ is much faster.)

     The fourth form generates the integer sequence ‘1, 2, ...,
     length(along.with)’.  (‘along.with’ is usually abbreviated to
     ‘along’, and ‘seq_along’ is much faster.)

     The fifth form generates the sequence ‘1, 2, ..., length(from)’
     (as if argument ‘along.with’ had been specified), _unless_ the
     argument is numeric of length 1 when it is interpreted as ‘1:from’
     (even for ‘seq(0)’ for compatibility with S).  Using either
     ‘seq_along’ or ‘seq_len’ is much preferred (unless strict S
     compatibility is essential).

     The final form generates the integer sequence ‘1, 2, ...,
     length.out’ unless ‘length.out = 0’, when it generates
     ‘integer(0)’.

     Very small sequences (with ‘from - to’ of the order of 10^{-14}
     times the larger of the ends) will return ‘from’.

     For ‘seq’ (only), up to two of ‘from’, ‘to’ and ‘by’ can be
     supplied as complex values provided ‘length.out’ or ‘along.with’
     is specified.  More generally, the default method of ‘seq’ will
     handle classed objects with methods for the ‘Math’, ‘Ops’ and
     ‘Summary’ group generics.

    

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 5 - Vectorized functions <a class="anchor" id="DS102L1-WS.5_page_5"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

Something that makes R so powerful is that many of R's functions take vectors as arguments. These vectorized functions are usually extremely fast and efficient. 

In [21]:
mean(phone.number.vector)

[1] 3

In [22]:
length(phone.number.vector)

[1] 7

In [23]:
min(phone.number.vector)

[1] 1

In [24]:
max(phone.number.vector)

[1] 5

In [25]:
sd(phone.number.vector)

[1] 1.914854

In [26]:
sum(c(1, 2, 3)) 

[1] 6

In practical settings, such as when reading data from files, it is common to have NA values in vectors

In [27]:
messy.vector <- c(8, 6, NA, 7, 5, NA, 3, 0, 9)

In [28]:
messy.vector

[1]  8  6 NA  7  5 NA  3  0  9

In [29]:
length(messy.vector)

[1] 9

In [30]:
#notice an NA when trying to run a function on this vector
mean(messy.vector) 

[1] NA

In [31]:
#let's remove those vectors
mean(messy.vector, na.rm=TRUE)

[1] 5.428571

In [32]:
# here again notice the NA when trying to run a function on this vector
sum(messy.vector, na.rm=FALSE)

[1] NA

In [33]:
sum(messy.vector, na.rm=TRUE)

[1] 38

Vectors can be constructed from logical values as well

In [34]:
log.vector <- c(TRUE, TRUE, FALSE) 

In [35]:
log.vector

[1]  TRUE  TRUE FALSE

Since logical values can be coerced into behaving like numerics, as we saw earlier, if we try to sum a logical vector as follows

In [36]:
sum(log.vector)

[1] 2

In [37]:
log.vector[c(1,2,3)]

[1]  TRUE  TRUE FALSE

In [38]:
log.vector[1]

[1] TRUE

In [39]:
#let's go back to our messy.vector
messy.vector

[1]  8  6 NA  7  5 NA  3  0  9

In [40]:
# we can run a boolean isna to check to see which ones are NA
is.na(messy.vector)

[1] FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE

In [41]:
# then we can also count how many we have
sum(is.na(messy.vector)) 

[1] 2

When you use Boolean operators on vectors, they also return logical vectors of the same length as the vector being operated on

In [42]:
phone.number.vector > 4

[1]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE

In [43]:
sum(phone.number.vector > 4) 

[1] 3

We can use vectors to subset other vectors. When we subset vectors using logical vectors of the same length, only the elements corresponding to the TRUE values are extracted. Hopefully, light bulbs are starting to go off in your head. If we wanted to extract only the legitimate non-NA digits from our messy.vector, we can do it as follows:

In [44]:
messy.vector

[1]  8  6 NA  7  5 NA  3  0  9

In [45]:
messy.vector[!is.na(messy.vector)] 

[1] 8 6 7 5 3 0 9

Voila' we have a vector without NAs just by subsetting using a boolean function :)

Similarly, we can show all the digits in our phone number that are greater than four as follows:

In [46]:
phone.number.vector[phone.number.vector> 4]

[1] 5 5 5

So far, we've only been displaying elements that have been extracted from a vector. However, just as we've been assigning and reassigning variables, we can assign values to various indices of a vector and change the vector as a result. For example, if we changed our phone number and we have a change in the first digit of our number (it's really 8), we can reassign just that element without modifying the others:

In [47]:
phone.number.vector

[1] 5 5 5 1 2 1 2

In [48]:
phone.number.vector[1] <- 8

In [49]:
phone.number.vector

[1] 8 5 5 1 2 1 2

Sometimes, it may be required to replace all the NA values in a vector with the value 0. To do this with our messy vector, we can execute the following command:

In [50]:
messy.vector[is.na(messy.vector)] <- 0

In [51]:
messy.vector

[1] 8 6 0 7 5 0 3 0 9

Elegant though the preceding solution is, modifying a vector in place is usually discouraged in favor of creating a copy of the original vector and modifying the copy. One such technique to perform this is using the ifelse() function.

Not to be confused with the if/else control construct, ifelse() is a function that takes three arguments: a test that returns a logical/Boolean value, a value to use if the element passes the test, and one to return if the element fails the test.

The preceding in-place modification solution could be reimplemented with ifelse as follows:

In [52]:
messy.vector <- c(8, 6, NA, 7, 5, NA, 3, 0, 9)

In [53]:
messy.vector

[1]  8  6 NA  7  5 NA  3  0  9

In [54]:
ifelse(is.na(messy.vector), 0, messy.vector) 

[1] 8 6 0 7 5 0 3 0 9

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 6 - Recycling <a class="anchor" id="DS102L1-WS.5_page_6"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

One last important property of vectors and vector operations in R is that they can be recycled. To understand what I mean, examine the following expression:

In [55]:
phone.number.vector + 1

[1] 9 6 6 2 3 2 3

This expression adds 1 to each digit in the phone number. Although it may look so, R is not performing this operation between a vector and a single value. What is really happening here is that R is told to perform element-wise addition on a vector of length 7 and a vector of length 1. As element-wise addition is not defined for vectors of differing lengths, R recycles the smaller vector until it reaches the same length as that of the bigger vector. Once both the vectors are the same size, then R, element by element, performs the addition and returns the result. This is the same as below:

In [56]:
phone.number.vector + c(1, 1, 1, 1, 1, 1, 1) 

[1] 9 6 6 2 3 2 3

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 7 - Functions <a class="anchor" id="DS102L1-WS.5_page_7"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

If we need to perform some computation that isn't already a function in R a multiple number of times, we usually do so by defining our own functions. A custom function in R is defined using the following syntax:

```r
function.name <- function(argument1, argument2, ...){ 
   # some functionality 
}
```

In [57]:
# function to determine if number is even
is.even <- function(a.number){ 
  remainder <- a.number %% 2 
  if(remainder==0) 
   return(TRUE) 
   return(FALSE) 
} 

In [58]:
is.even(9)

[1] FALSE

In [59]:
is.even(10)

[1] TRUE

As an example of a function that takes more than one argument, let's generalize the preceding function by creating a function that determines whether the first argument is divisible by its second argument:

In [60]:
is.divisible.by <- function(large.number, smaller.number){ 
   if(large.number %% smaller.number != 0) 
   return(FALSE) 
   return(TRUE) 
} 

In [61]:
is.divisible.by(10,2)

[1] TRUE

In [62]:
is.divisible.by(10,3)

[1] FALSE

In [63]:
is.divisible.by(9,3)

[1] TRUE

It is very common in R to want to apply a particular function to every element of a vector. Instead of using a loop to iterate over the elements of a vector, as we would do in many other languages, we use a function called sapply() to perform this. sapply() takes a vector and a function as its arguments. It then applies the function to every element and returns a vector of results. 

In [64]:
?sapply

lapply                  package:base                   R Documentation

_A_p_p_l_y _a _F_u_n_c_t_i_o_n _o_v_e_r _a _L_i_s_t _o_r _V_e_c_t_o_r

_D_e_s_c_r_i_p_t_i_o_n:

     ‘lapply’ returns a list of the same length as ‘X’, each element of
     which is the result of applying ‘FUN’ to the corresponding element
     of ‘X’.

     ‘sapply’ is a user-friendly version and wrapper of ‘lapply’ by
     default returning a vector, matrix or, if ‘simplify = "array"’, an
     array if appropriate, by applying ‘simplify2array()’.  ‘sapply(x,
     f, simplify = FALSE, USE.NAMES = FALSE)’ is the same as ‘lapply(x,
     f)’.

     ‘vapply’ is similar to ‘sapply’, but has a pre-specified type of
     return value, so it can be safer (and sometimes faster) to use.

     ‘replicate’ is a wrapper for the common use of ‘sapply’ for
     repeated evaluation of an expression (which will usually involve
     random number generation).

     ‘simplify2array()’ is the utility called from ‘sapply()’ when
     ‘simplify’ is not false and is similarly called from ‘mapply()’.

_U_s_a_g_e:

     lapply(X, FUN, ...)
     
     sapply(X, FUN, ..., simplify = TRUE, USE.NAMES = TRUE)
     
     vapply(X, FUN, FUN.VALUE, ..., USE.NAMES = TRUE)
     
     replicate(n, expr, simplify = "array")
     
     simplify2array(x, higher = TRUE, except = c(0L, 1L))
     
_A_r_g_u_m_e_n_t_s:

       X: a vector (atomic or list) or an ‘expression’ object.  Other
          objects (including classed objects) will be coerced by
          ‘base::as.list’.

     FUN: the function to be applied to each element of ‘X’: see
          ‘Details’.  In the case of functions like ‘+’, ‘%*%’, the
          function name must be backquoted or quoted.

     ...: optional arguments to ‘FUN’.

simplify: logical or character string; should the result be simplified
          to a vector, matrix or higher dimensional array if possible?
          For ‘sapply’ it must be named and not abbreviated.  The
          default value, ‘TRUE’, returns a vector or matrix if
          appropriate, whereas if ‘simplify = "array"’ the result may
          be an ‘array’ of “rank” (=‘length(dim(.))’) one higher than
          the result of ‘FUN(X[[i]])’.

USE.NAMES: logical; if ‘TRUE’ and if ‘X’ is character, use ‘X’ as
          ‘names’ for the result unless it had names already.  Since
          this argument follows ‘...’ its name cannot be abbreviated.

FUN.VALUE: a (generalized) vector; a template for the return value from
          FUN.  See ‘Details’.

       n: integer: the number of replications.

    expr: the expression (a language object, usually a call) to
          evaluate repeatedly.

       x: a list, typically returned from ‘lapply()’.

  higher: logical; if true, ‘simplify2array()’ will produce a (“higher
          rank”) array when appropriate, whereas ‘higher = FALSE’ would
          return a matrix (or vector) only.  These two cases correspond
          to ‘sapply(*, simplify = "array")’ or ‘simplify = TRUE’,
          respectively.

  except: integer vector or ‘NULL’; the default ‘c(0L, 1L)’ corresponds
          to the exceptions used by ‘sapply’: a list with elements of
          common length 0 or 1 is not simplified to an array but is
          returned, respectively, as is or unlisted.  These exceptions
          can be disabled by specifying only a subset of ‘0:1’, or
          ‘NULL’ to always simplify to an array (if possible).

_D_e_t_a_i_l_s:

     ‘FUN’ is found by a call to ‘match.fun’ and typically is specified
     as a function or a symbol (e.g., a backquoted name) or a character
     string specifying a function to be searched for from the
     environment of the call to ‘lapply’.

     Function ‘FUN’ must be able to accept as input any of the elements
     of ‘X’.  If the latter is an atomic vector, ‘FUN’ will always be
     passed a length-one vector of the same type as ‘X’.

     Arguments in ‘...’ cannot

In [65]:
sapply(phone.number.vector, is.even) 

[1]  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE

This worked great because sapply takes each element and uses it as the argument in is.even(), which takes only one argument. If you wanted to find the digits that are divisible by three, it would require a little bit more work.

One option is just to define a function,  is.divisible.by.three(), that takes only one argument and use this in sapply. The more common solution, however, is to define an unnamed function that does just that in the body of the sapply function call:

In [66]:
sapply(phone.number.vector, function(num){is.divisible.by(num, 2)}) 

[1]  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE

In [67]:
phone.number.vector

[1] 8 5 5 1 2 1 2

Here, we essentially created a function that checks whether its argument is divisible by three, except we don't assign it to a variable and use it directly in the sapply body instead. These one-time-use unnamed functions are called anonymous functions or lambda functions. (The name comes from [Alonzo Church](https://en.wikipedia.org/wiki/Alonzo_Church)'s invention of the [lambda calculus](https://en.wikipedia.org/wiki/Lambda_calculus))

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 8 - Matrices <a class="anchor" id="DS102L1-WS.5_page_8"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

In addition to the vector data structure, R has the matrix, data frame, list, and array data structures. 

A matrix in R, like in math, is a rectangular array of values (of one type) arranged in rows and columns and can be manipulated as a whole. Operations on matrices are fundamental to data analysis.

One way of creating a matrix is to just supply a vector to the matrix() function:

In [68]:
a.matrix <- matrix(c(1, 2, 3, 4, 5, 6)) 
a.matrix

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6

This produces a matrix with all the supplied values in a single column. We can make a similar matrix with two columns by supplying matrix() with an optional argument, ncol, that specifies the number of columns:

In [69]:
a.matrix <- matrix(c(1, 2, 3, 4, 5, 6), ncol=2) 
a.matrix 

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

We could have produced the same matrix by binding two vectors, c(1, 2, 3) and c(4, 5, 6), by columns using the cbind() function as follows:

In [70]:
a2.matrix <- cbind(c(1, 2, 3), c(4, 5, 6)) 
a2.matrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

We could create the transposition of this matrix (where rows and columns are switched) by binding these vectors by row instead:

In [71]:
a3.matrix <- rbind(c(1, 2, 3), c(4, 5, 6)) 
a3.matrix 

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

We can do this by just using the matrix transposition function in R, t():

In [72]:
t(a2.matrix)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

Some other functions that operate on whole vectors are rowSums()/colSums() and rowMeans()/colMeans():

In [73]:
a2.matrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [74]:
colSums(a2.matrix)

[1]  6 15

In [75]:
rowMeans(a2.matrix)

[1] 2.5 3.5 4.5

If vectors have sapply(), then matrices have apply(). The preceding two functions could have been written, more verbosely, as follows:

In [76]:
apply(a2.matrix, 2, sum) 

[1]  6 15

In [77]:
apply(a2.matrix, 1, mean) 

[1] 2.5 3.5 4.5

Here, 1 instructs R to perform the supplied function over its rows, and 2, over its columns.

The matrix multiplication operator in R is *:

In [78]:
a2.matrix * a2.matrix

[,1] [,2]
[1,] 1    16  
[2,] 4    25  
[3,] 9    36

Remember, matrix multiplication is only defined for matrices where the number of columns in the first matrix is equal to the number of rows in the second:

In [79]:
a2.matrix

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [80]:
a3.matrix 

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [81]:
a2.matrix * a3.matrix

ERROR: Error in a2.matrix * a3.matrix: non-conformable arrays


In [ ]:
#dim() function shows us the dimensions of the matrix
dim(a2.matrix)

In [ ]:
dim(a3.matrix)

To index the element of a matrix at the second row and first column, you need to supply both of these numbers into the subscripting operator:

In [ ]:
a2.matrix[2,1]

Many useRs get confused and forget the order in which the indices must appear; remember, it's row first, then columns!

If you leave one of the spaces empty, R will assume that you want that whole dimension:

In [ ]:
# returns the first row 
a2.matrix[1,]

In [ ]:
# returns the whole second column 
a2.matrix[,2] 

In [ ]:
#we can use vectors in our subscript operator:
# give me element in column 2 at the first and third row 
a2.matrix[c(1, 3), 2] 

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 9 - Loading data into R <a class="anchor" id="DS102L1-WS.5_page_9"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

Thus far, we've only been entering data directly into the interactive R console of this Jupyter notebook. For any dataset of non-trivial size, this is, obviously, not an option. Fortunately for us, R has a robust suite of functions to read data directly from external files.

Go ahead and create a file on your hard disk called favorites.txt that looks like this:

```text
flavor,number 
pistachio,6 
mint chocolate chip,7 
vanilla,5
chocolate,10 
strawberry,2 
neopolitan,4 
```

or just read it in from a file location used in this companion notebook.

In [ ]:
favs <- read.table("../../../Data/favorites.txt", sep=",", header=TRUE) 

In [ ]:
favs

If you get an error that there is no such file or directory, give R the full path name to your dataset or, alternatively, run the following command in an R console/terminal as the below will not work in Jupyter:


```r
favs <- read.table(file.choose(), sep=",", header=TRUE)
```

Note this can only be performed in the R console/Terminal with the full absolute path shown below

<p style="text-align: center">
  <img  src="../../../Media/R-File-Choose.png" width="600" alt="R-Terminal">
</p>


The sep="," argument tells R that each data element in a row is separated by a comma. Other common data formats have values separated by tabs and pipes ("|"). The value of sep should then be "\t" and "|", respectively.

The header=TRUE argument tells R that the first row of the file should be interpreted as the names of the columns. Remember, you can enter ?read.table at the console to learn more about these options.

Reading from files in this comma-separated values format (usually with the .csv file extension) is so common that R has a more specific function just for it. The preceding data import expression can be best written simply as follows:

In [ ]:
favs <- read.csv("../../../Data/favorites.txt") 

Now, we have the data in the file held in a variable of the data.frame class. A data frame can be thought of as a rectangular array of data that you might see in a spreadsheet application. In this way, a data frame can also be thought of as a matrix; indeed, we can use matrix-style indexing to extract elements from it. A data frame differs from a matrix, though, in that a data frame may have columns of differing types. For example, whereas a matrix would only allow one of these types, the dataset that we just loaded contains character data in its first column and numeric data in its second column.

Let's check out what we have using the head() command, which will show us the first few lines of a data frame:

In [ ]:
head(favs)

Let's take a look at the class to ensure what I'm thinking is correct 

In [ ]:
class(favs)

next lets address each column to see what type they are

In [ ]:
class(favs$flavor)

In [ ]:
class(favs$number)

Technically, flavor is a factor data type, not a character type.

We haven't seen factors yet, but the idea behind them is really simple. Essentially, factors are codings for categorical variables, which are variables that take on one of a finite number of categories--think {"high", "medium", and "low"} or {"control", "experimental"}.

Though factors are extremely useful in statistical modeling in R, the fact that R, by default, automatically interprets a column from the data read from disk as a type factor if it contains characters is something that trips up novices and seasoned useRs alike. Due to this, we will primarily prevent this behavior manually by adding the stringsAsFactors optional keyword argument to the read.* commands:

new operator on you **$**, the extract operator. You can extract each column using it. But there also several other ways to extract a single column of data

In [ ]:
favs$flavor

In [ ]:
favs[["flavor"]] 

In [ ]:
favs[,1] 

You can use the names() function to get a list of the columns available in a data frame. You can even reassign names using the same:

In [ ]:
names(favs)

In [ ]:
names(favs)[1] <- "flav" 

In [ ]:
names(favs)

Lastly, we can get a compact display of the structure of a data frame using the str() function on it:

In [ ]:
#str is Structure for short
str(favs) 

Actually, you can use this function on any R structure--the property of functions that change their behavior based on the type of input is called polymorphism.

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 10 - Working with Packages <a class="anchor" id="DS102L1-WS.5_page_10"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

Robust and numerous though base R functions are, we are by no means limited to them. Additional functionality is available in the form of packages. In fact, what makes R such a formidable statistics platform is the astonishing wealth of packages available (over 10,000). R's ecosystem is huge!

Most of these myriad packages exist on the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/). CRAN is the primary repository for user-created packages.

One package that we are going to start using right away is the ggplot2 package. ggplot2 is a plotting system for R. Base R has sophisticated and advanced mechanisms to plot data, but many find ggplot2 more consistent and easier to use. Further, the plots are often more aesthetically pleasing by default.

In [ ]:
# downloads and installs from CRAN 
install.packages("ggplot2") 

Now that we have the package downloaded, we need to load it into the R session.

In [ ]:
# load library
library(ggplot2)

In [ ]:
ggplot(favs, aes(x=flav, y=number)) +  geom_bar(stat="identity") + ggtitle("Soy ice cream flavor preferences") 

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 11 - Summary <a class="anchor" id="DS102L1-WS.5_page_11"></a>

[Back to Top](#DS102L1-WS.5_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


In this session, you learned about one of the world's greatest free analytics platform, R. 

You now know how to:

- Use R as a calculator to do arithmetic
- Make vectors, operate on them, and subset them expressively
- Load data from disk
- Install packages

You have by no means finished learning about R; indeed, we have gone over mostly just the basics. However, we have enough to continue ahead, and you'll pick up more along the way. Onward to statistics land!