In [63]:
# packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import pickle

In [2]:
# packages
#import pandas as pd
#import numpy as np
#from sklearn.preprocessing import StandardScaler
#from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
#from sklearn import metrics
#import pickle

In [3]:
# data
data = pd.read_csv('data.csv')

## Inspection

In [4]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
data.shape
# 33 columns, 569 rows

(569, 33)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [7]:
# copy for targets
df = data.copy()

In [8]:
df = df.drop(['id', 'Unnamed: 32'], axis = 1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [10]:
# view all columns & rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [11]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M       17.990         10.38          122.80     1001.0   
1           M       20.570         17.77          132.90     1326.0   
2           M       19.690         21.25          130.00     1203.0   
3           M       11.420         20.38           77.58      386.1   
4           M       20.290         14.34          135.10     1297.0   
5           M       12.450         15.70           82.57      477.1   
6           M       18.250         19.98          119.60     1040.0   
7           M       13.710         20.83           90.20      577.9   
8           M       13.000         21.82           87.50      519.8   
9           M       12.460         24.04           83.97      475.9   
10          M       16.020         23.24          102.70      797.8   
11          M       15.780         17.89          103.60      781.0   
12          M       19.170         24.80          132.40     1123.0   
13          M       15.850         23.95          103.70      782.7   
14          M       13.730         22.61           93.60      578.3   
15          M       14.540         27.54           96.73      658.8   
16          M       14.680         20.13           94.74      684.5   
17          M       16.130         20.68          108.10      798.8   
18          M       19.810         22.15          130.00     1260.0   
19          B       13.540         14.36           87.46      566.3   
20          B       13.080         15.71           85.63      520.0   
21          B        9.504         12.44           60.34      273.9   
22          M       15.340         14.26          102.50      704.4   
23          M       21.160         23.04          137.20     1404.0   
24          M       16.650         21.38          110.00      904.6   
25          M       17.140         16.40          116.00      912.7   
26          M       14.580         21.53           97.41      644.8   
27          M       18.610         20.25          122.10     1094.0   
28          M       15.300         25.27          102.40      732.4   
29          M       17.570         15.05          115.00      955.1   
30          M       18.630         25.11          124.80     1088.0   
31          M       11.840         18.70           77.93      440.6   
32          M       17.020         23.98          112.80      899.3   
33          M       19.270         26.47          127.90     1162.0   
34          M       16.130         17.88          107.00      807.2   
35          M       16.740         21.59          110.10      869.5   
36          M       14.250         21.72           93.63      633.0   
37          B       13.030         18.42           82.61      523.8   
38          M       14.990         25.20           95.54      698.8   
39          M       13.480         20.82           88.40      559.2   
40          M       13.440         21.58           86.18      563.0   
41          M       10.950         21.35           71.90      371.1   
42          M       19.070         24.81          128.30     1104.0   
43          M       13.280         20.28           87.32      545.2   
44          M       13.170         21.81           85.42      531.5   
45          M       18.650         17.60          123.70     1076.0   
46          B        8.196         16.84           51.71      201.9   
47          M       13.170         18.66           85.98      534.6   
48          B       12.050         14.63           78.04      449.3   
49          B       13.490         22.30           86.91      561.0   
50          B       11.760         21.60           74.72      427.9   
51          B       13.640         16.34           87.21      571.8   
52          B       11.940         18.24           75.71      437.6   
53          M       18.220         18.70          120.30     1033.0   
54          M       15.100         22.02           97.26      712.8   
55          B       11.520  

In [12]:
# revert to reasonable viewing length
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20

## task is to predict whether breast cancer is benign or malignant

In [13]:
list(df.columns)

['diagnosis',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [14]:
df['diagnosis']

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [15]:
df['diagnosis'].value_counts()
# 212 malignant case, 357 benign

B    357
M    212
Name: diagnosis, dtype: int64

In [16]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [17]:
targets = np.where(df['diagnosis'] == 'M', 1,0)

In [18]:
df['malignant'] = targets

In [19]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  texture_worst  perimeter_worst  area_worst  \
0         0.2419  ...          17.33           184.60      2019.0   
1         0.1812  ...          23.41           158.80      1956.0   
2         0.2069  ...          25.53           152.50      1709.0   
3         0.2597  ...          26.50            98.87       567.7   
4         0.1809  ...          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  malignant  
0          0.4601                  0.11890          1  
1          0.2750                  0.08902          1  
2          0.3613                  0.08758          1  
3          0.6638                  0.17300          1  
4          0.2364                  0.07678          1  

[5 rows x 32 columns]

In [20]:
# drop diagnosis since malignant columns accounts
DF = df.drop(['diagnosis'], axis = 1)

In [21]:
DF.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  texture_worst  perimeter_worst  area_worst  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  malignant  
0          0.4601                  0.11890          1  
1          0.2750                  0.08902          1  
2          0.3613                  0.08758          1  
3          0.6638                  0.17300          1  
4          0.2364                  0.07678          1  

[5 rows x 31 columns]

## Logistic Regression to predict malignancy

In [22]:
data_with_targets = DF

In [23]:
data_with_targets.shape
# data with targets has 32 columns & 569 rows

(569, 31)

In [24]:
# select inputs for regression
data_with_targets.iloc[:, :-1]

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [25]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

In [26]:
unscaled_inputs.columns.values

array(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se',
       'smoothness_se', 'compactness_se', 'concavity_se',
       'concave points_se', 'symmetry_se', 'fractal_dimension_se',
       'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst',
       'smoothness_worst', 'compactness_worst', 'concavity_worst',
       'concave points_worst', 'symmetry_worst',
       'fractal_dimension_worst'], dtype=object)

## Standardize the data

In [27]:
malignancy_scaler = StandardScaler()

In [28]:
malignancy_scaler.fit(unscaled_inputs)

StandardScaler()

In [29]:
scaled_inputs = malignancy_scaler.transform(unscaled_inputs)

In [30]:
scaled_inputs

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

## Split data into train & test, then shuffle

In [31]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = .7, random_state = 20)
# random state to shuffle observations in same way

In [32]:
print(x_train.shape, y_train.shape)

(398, 30) (398,)


In [33]:
print(x_test.shape, y_test.shape)

(171, 30) (171,)


## Logistic Regression with SkLearn

In [34]:
# train the model
reg = LogisticRegression()

In [35]:
reg.fit(x_train, y_train)

LogisticRegression()

In [36]:
# evaluate model accuracy
reg.score(x_train, y_train)

0.9849246231155779

In [37]:
# In conclusion: utilizing logistic regression to predict breast cancer malignancy has an accuracy of just above 98%
# i.e.: the model learned to classify ~98% of the observations correctly

## Manually inspect accuracy of the model 

In [38]:
model_outputs = reg.predict(x_train)

In [40]:
# to view entire array
np.set_printoptions(threshold=np.inf)

In [41]:
model_outputs

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,

In [42]:
y_train

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,

In [43]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [44]:
#finding the intercepts and coefficients

In [45]:
reg.intercept_

array([-0.03665266])

In [46]:
reg.coef_

array([[ 0.24054411,  0.36800324,  0.2150547 ,  0.31616264,  0.4220075 ,
        -0.47702584,  0.79259038,  0.99101658, -0.37444546, -0.22203392,
         1.3589787 , -0.01775894,  0.52668045,  1.00220402,  0.13844823,
        -0.61934081, -0.20807163,  0.22473888, -0.35686779, -0.44306807,
         1.00998005,  1.0727926 ,  0.68635123,  0.91302594,  0.45052668,
        -0.05803534,  0.72799997,  0.91160916,  0.9197722 ,  0.49549568]])

In [47]:
unscaled_inputs.columns.values

array(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se',
       'smoothness_se', 'compactness_se', 'concavity_se',
       'concave points_se', 'symmetry_se', 'fractal_dimension_se',
       'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst',
       'smoothness_worst', 'compactness_worst', 'concavity_worst',
       'concave points_worst', 'symmetry_worst',
       'fractal_dimension_worst'], dtype=object)

In [48]:
feature_name = unscaled_inputs.columns.values

In [49]:
summary_table = pd.DataFrame(columns = ['Feature Name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0               radius_mean     0.240544
1              texture_mean     0.368003
2            perimeter_mean     0.215055
3                 area_mean     0.316163
4           smoothness_mean     0.422007
..                      ...          ...
25        compactness_worst    -0.058035
26          concavity_worst     0.728000
27     concave points_worst     0.911609
28           symmetry_worst     0.919772
29  fractal_dimension_worst     0.495496

[30 rows x 2 columns]

In [52]:
pd.options.display.max_rows = None

In [53]:
summary_table

Feature Name  Coefficient
0               radius_mean     0.240544
1              texture_mean     0.368003
2            perimeter_mean     0.215055
3                 area_mean     0.316163
4           smoothness_mean     0.422007
5          compactness_mean    -0.477026
6            concavity_mean     0.792590
7       concave points_mean     0.991017
8             symmetry_mean    -0.374445
9    fractal_dimension_mean    -0.222034
10                radius_se     1.358979
11               texture_se    -0.017759
12             perimeter_se     0.526680
13                  area_se     1.002204
14            smoothness_se     0.138448
15           compactness_se    -0.619341
16             concavity_se    -0.208072
17        concave points_se     0.224739
18              symmetry_se    -0.356868
19     fractal_dimension_se    -0.443068
20             radius_worst     1.009980
21            texture_worst     1.072793
22          perimeter_worst     0.686351
23               area_worst     0.913026
24         smoothness_worst     0.450527
25        compactness_worst    -0.058035
26          concavity_worst     0.728000
27     concave points_worst     0.911609
28           symmetry_worst     0.919772
29  fractal_dimension_worst     0.495496

In [54]:
summary_table.index = summary_table.index + 1
summary_table.iloc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
1                 Intercept    -0.036653
2              texture_mean     0.368003
3            perimeter_mean     0.215055
4                 area_mean     0.316163
5           smoothness_mean     0.422007
6          compactness_mean    -0.477026
7            concavity_mean     0.792590
8       concave points_mean     0.991017
9             symmetry_mean    -0.374445
10   fractal_dimension_mean    -0.222034
11                radius_se     1.358979
12               texture_se    -0.017759
13             perimeter_se     0.526680
14                  area_se     1.002204
15            smoothness_se     0.138448
16           compactness_se    -0.619341
17             concavity_se    -0.208072
18        concave points_se     0.224739
19              symmetry_se    -0.356868
20     fractal_dimension_se    -0.443068
21             radius_worst     1.009980
22            texture_worst     1.072793
23          perimeter_worst     0.686351
24               area_worst     0.913026
25         smoothness_worst     0.450527
26        compactness_worst    -0.058035
27          concavity_worst     0.728000
28     concave points_worst     0.911609
29           symmetry_worst     0.919772
30  fractal_dimension_worst     0.495496

In [55]:
# displaying and interpreting the coefficients 

In [56]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds_ratio
1                 Intercept    -0.036653    0.964011
2              texture_mean     0.368003    1.444847
3            perimeter_mean     0.215055    1.239930
4                 area_mean     0.316163    1.371853
5           smoothness_mean     0.422007    1.525020
6          compactness_mean    -0.477026    0.620626
7            concavity_mean     0.792590    2.209111
8       concave points_mean     0.991017    2.693972
9             symmetry_mean    -0.374445    0.687671
10   fractal_dimension_mean    -0.222034    0.800888
11                radius_se     1.358979    3.892216
12               texture_se    -0.017759    0.982398
13             perimeter_se     0.526680    1.693302
14                  area_se     1.002204    2.724280
15            smoothness_se     0.138448    1.148490
16           compactness_se    -0.619341    0.538299
17             concavity_se    -0.208072    0.812149
18        concave points_se     0.224739    1.251996
19              symmetry_se    -0.356868    0.699865
20     fractal_dimension_se    -0.443068    0.642063
21             radius_worst     1.009980    2.745546
22            texture_worst     1.072793    2.923532
23          perimeter_worst     0.686351    1.986454
24               area_worst     0.913026    2.491851
25         smoothness_worst     0.450527    1.569138
26        compactness_worst    -0.058035    0.943617
27          concavity_worst     0.728000    2.070935
28     concave points_worst     0.911609    2.488323
29           symmetry_worst     0.919772    2.508719
30  fractal_dimension_worst     0.495496    1.641312

## Testing the model

In [57]:
# based on data the model has never seen before
reg.score(x_test, y_test)
# in 98% of the cases, the model predicted whether a diagnosis was malignant or not

0.9824561403508771

In [58]:
# examine the probability of an output being 0 or 1

In [60]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba # first column shows probability of being 0, second column: probability of being 1

array([[9.99099369e-01, 9.00631077e-04],
       [6.75292230e-01, 3.24707770e-01],
       [7.79649177e-08, 9.99999922e-01],
       [9.83653819e-01, 1.63461809e-02],
       [4.60974362e-03, 9.95390256e-01],
       [3.69176378e-09, 9.99999996e-01],
       [3.92889123e-06, 9.99996071e-01],
       [9.63774957e-01, 3.62250434e-02],
       [9.98769507e-01, 1.23049311e-03],
       [5.05817610e-13, 1.00000000e+00],
       [1.01196015e-03, 9.98988040e-01],
       [9.99492008e-01, 5.07992042e-04],
       [9.60500717e-01, 3.94992830e-02],
       [3.38972293e-06, 9.99996610e-01],
       [8.16863396e-01, 1.83136604e-01],
       [9.68304910e-01, 3.16950901e-02],
       [9.99566379e-01, 4.33620668e-04],
       [1.15418949e-01, 8.84581051e-01],
       [3.24538398e-03, 9.96754616e-01],
       [9.98926898e-01, 1.07310177e-03],
       [9.87250767e-01, 1.27492328e-02],
       [9.99974990e-01, 2.50103006e-05],
       [2.29503527e-02, 9.77049647e-01],
       [2.98202441e-03, 9.97017976e-01],
       [6.399455

In [61]:
### Next steps
## Save the model
## Create the model
## Get new data, classify it, pass it through SQL & analyze it in Tableau

In [64]:
with open('LogRedModel', 'wb') as file:
    pickle.dump(reg, file)

In [65]:
with open('MalignancyScaler', 'wb') as file:
    pickle.dump(malignancy_scaler, file)