# R Structure

#### Basic Key terms:
- Columns is known as properties
- Variables inside Columns is also known as features/variables
- Rows is collection of items/observations


---
#### Data Structure in R:
- vector
- matrix
- array
- factor
- ts
- data.frame
- list

---

source: https://www.youtube.com/watch?v=92YFZhKSJq0

<p style="text-align: left">
  <img  src="../../../Media/julie/r-structure.png" width="1100" alt="R Structure">
</p>

---

#### vector:
- 1 Dimensional
    - variables one after another
        - example: ages, 
- 1 Data Type
    - needs to be same data type, cannot mix data type
    - numeric, strings 

#### matrix:
- 2 Dimensional
    - columns and rows
- 1 Data Type
    - needs to be same data type, in each column, cannot mix data type
    - numeric, strings 

#### array:
- n(many) Dimensional
    - 3+ dimensional objects
- 1 Data Type
   - each array has same data type

#### factor:
- 1 Dimensional
    - variables one after another
    - is just likea vector, except...
    - the features for the columns have specified levels
        - example: sex, grades, or type of membership
        
- 1 Data Type
    - needs to be same data type, cannot mix data type
    - numeric, strings

#### ts(time-series):
- 1-2 Dimensional
    - will not get into this
- Many Data Types
    - will not get into this

#### data.frame:
- 2 Dimensional
    - columns and rows
    - these have column anmes, data frames are much easier to subset/sunscripting
    
- Many Data Types
     - unlike matrix, can store different data types in the same data frame 
     - but has limitations: only use 1 store 1 type of data in each column

#### list:
- n(many) Dimensional
    - complex, you can store objects within objects
    - hard to subscript
    - you still have to use them
    
- Many Data Types
    - many data types in the list

---

# Vectors:

In [2]:
x <- 11
x

[1] 11

In [3]:
# create numeric vector
x1 <- c(1,2,3,4,5)
x1

[1] 1 2 3 4 5

In [4]:
# create categorical vector
gender <- c("male", "female")
gender

[1] "male"   "female"

In [5]:
# sequence
2:7

[1] 2 3 4 5 6 7

In [6]:
# general sequence
# sequence 1:7, in increments of 1
seq(from=1, to=7, by =1)

[1] 1 2 3 4 5 6 7

In [9]:
# create a vector, repeating the number 1, 10 times
rep(1, times=10)

[1] 1 1 1 1 1 1 1 1 1 1

In [10]:
# create a vector, repeating "marin", 5 times
rep("marin", times=5)

[1] "marin" "marin" "marin" "marin" "marin"

In [12]:
# create a vector, repeating a sequence of numbers 1-3, 5 times
rep(1:3,times=5)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [14]:
# create a vector, repeating a sequence of non-intergers 2-5, increments of .25 , 5 times
rep(seq(from=2, to=5, by=0.25), times=5)

[1] 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25
[16] 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25 2.50 2.75
[31] 3.00 3.25 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25 2.50 2.75 3.00 3.25
[46] 3.50 3.75 4.00 4.25 4.50 4.75 5.00 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75
[61] 4.00 4.25 4.50 4.75 5.00

In [15]:
# create a vector, repeating characters, 5 times
rep(c("M", "N"), times=5)

[1] "M" "N" "M" "N" "M" "N" "M" "N" "M" "N"

In [16]:
# create 2 vectors
x<- 1:5
y<- c(1,3,5,7,9)

In [20]:
# add 10 to each variable in vector
x + 10

[1] 11 12 13 14 15

In [21]:
# multiple 10 to each variable in vector
x * 10

[1] 10 20 30 40 50

In [22]:
# if two vectors are of the same length, you may add, sub, mul, and div
# like the exmaple above

x+y

[1]  2  5  8 11 14

In [23]:
x-y

[1]  0 -1 -2 -3 -4

In [24]:
# extracting elements:
x

[1] 1 2 3 4 5

In [25]:
y

[1] 1 3 5 7 9

In [26]:
# extracting 3rd element
y[3]

[1] 5

In [27]:
# extracting all, except 3rd element
y[-3]

[1] 1 3 7 9

In [28]:
# extracting 1-3 elements
y[1:3]

[1] 1 3 5

In [29]:
# extracting 1st and 5th elements
y[c(1,5)]

[1] 1 9

In [30]:
# extracting all, except 1st and 5th elements
y[-c(1,5)]

[1] 3 5 7

In [31]:
# extracting elements less than 6
y[y<6]

[1] 1 3 5

# Matrix

In [33]:
# creating a matrix with 3 rows, TRUE, to let R know to enter these elements (side to side)
matrix(c(1,2,3,4,5,6,7,8,9), nrow=3, byrow=TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [34]:
# if you set = FALSE, the elements will be entered in a columns wise fashion (up and down)
matrix(c(1,2,3,4,5,6,7,8,9), nrow=3, byrow=FALSE)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [36]:
# creating a matrix called mat
# with 3 rows, TRUE, to let R know to enter these elements (side to side)
mat <- matrix(c(1,2,3,4,5,6,7,8,9), nrow=3, byrow=TRUE)
mat

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [37]:
# extract element 1st row and 2nd column
mat[1,2]

[1] 2

In [38]:
# extract elements 1st and 3rd row and 2nd column
mat[c(1,3),2]

[1] 2 8

In [39]:
# extract all row 2, all columns (all elements in row 2)
mat[2,]

[1] 4 5 6

In [40]:
# extract all row 1, all columns (all elements in row 1)
mat[,1]

[1] 1 4 7

In [41]:
# you can take the martix and (+,-,*,/) the entire matrix
mat * 10

[,1] [,2] [,3]
[1,] 10   20   30  
[2,] 40   50   60  
[3,] 70   80   90

In [42]:
mat + 2

[,1] [,2] [,3]
[1,] 3     4    5  
[2,] 6     7    8  
[3,] 9    10   11

In [43]:
mat - 3.3

[,1] [,2] [,3]
[1,] -2.3 -1.3 -0.3
[2,]  0.7  1.7  2.7
[3,]  3.7  4.7  5.7

In [44]:
mat / 0.7

[,1]      [,2]      [,3]     
[1,]  1.428571  2.857143  4.285714
[2,]  5.714286  7.142857  8.571429
[3,] 10.000000 11.428571 12.857143