## Lesson 9 Hands-On Helper

### Create a five element array using numbers!

In [3]:
import numpy as np

In [4]:
NumbersAreFun = np.array([2,4,6,7,9,])

### Let's aggregate five functions on your array!

In [6]:
NumbersAreFun.max()

9

In [7]:
NumbersAreFun.min()

2

In [8]:
NumbersAreFun.mean()

5.6

In [9]:
NumbersAreFun.std()

2.4166091947189146

In [10]:
NumbersAreFun.sum()

28

### Create a five element array with only ones!

In [14]:
TwoIsAwesome = np.ones(5)
TwoIsAwesome 

array([1., 1., 1., 1., 1.])

### Add both dataframes together

In [15]:
TwoIsAwesome + NumbersAreFun

array([ 3.,  5.,  7.,  8., 10.])

### How about multiplying?

In [16]:
NumbersAreFun * 2

array([ 4,  8, 12, 14, 18])

### Calling the number in the third spot

In [17]:
NumbersAreFun[3]

7

### Four element-Two by Two matrix of numbers

In [18]:
MatrixFun = np.array([[1,3], [6, 4]])
MatrixFun

array([[1, 3],
       [6, 4]])

### Looking at the upper left in the matrix using indexing

In [20]:
MatrixFun[0,0]

1

### Finding the largest numbers in the Matrix

In [21]:
MatrixFun.max(axis=1)

array([3, 6])

### Reshape the Matrix!

In [24]:
MatrixFun.reshape(1,4)

array([[1, 3, 6, 4]])