In [1]:
import pandas as pd
import numpy as np

### Array

In [2]:
s = np.array(5)

In [3]:
x = s + 3

### Shape

In [4]:
s.shape

()

### Vectors

In [5]:
v = np.array([1,2,3])

In [6]:

v.shape

(3,)

### Matrice Transpose

In [11]:
m = np.array([[1,2,3],[4,5,6,],[7,8,9]])


In [12]:
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
inputs =np.array ([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [25]:
inputs.shape

(1, 4)

In [26]:
weights =np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [27]:
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [28]:
weights.shape

(3, 4)

### NumPy Quiz

In [58]:
def prepare_inputs(inputs):
    input_array = np.array([inputs])
    inputs_minus_min = input_array - np.min(input_array)
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)
    return input_array, inputs_minus_min, inputs_div_max


In [61]:
def multiply_inputs(m1, m2):
    
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)

In [62]:
def find_mean(values):
    return np.mean(values)

